using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;

namespace ProjectEuler.Tests
{
    [TestClass]
    public class Problem2
    {
        /// <summary>
        /// Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:
        ///
        /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        /// 
        /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
        /// </summary>
        [TestMethod]
        public void Run()
        {
            long sum = 0;

            List<long> fib = Fibonacci(4000000);

            foreach (long x in fib)
            {
                if (x % 2 == 0)
                {
                    sum += x;
                }
            }

            Assert.AreEqual(sum, 4613732);
        }

        private List<long> Fibonacci(long max)
        {
            List<long> fib = new List<long>();

            long a = 1;
            long b = 1;

            while (a + b < max)
            {
                long c = a + b;
                fib.Add(c);
                a = b;
                b = c;
            }

            return fib;
        }
    }
}
